module Env
  extend ActiveSupport::Concern
  SANDBOX=(ENV["RAILS_ENV"] == "development")
  EFIPAY_CLIENT_ID=(SANDBOX ? ENV["EFIPAY_CLIENT_ID_HOM"] : ENV["EFIPAY_CLIENT_ID_PROD"])
  EFIPAY_CLIENT_SECRET=(SANDBOX ? ENV["EFIPAY_CLIENT_SECRET_HOM"] : ENV["EFIPAY_CLIENT_SECRET_PROD"])
  EFIPAY_CERTIFICATE=(SANDBOX ? ENV["EFIPAY_CERTIFICATE_HOM"] : ENV["EFIPAY_CERTIFICATE_PROD"])
  EFIPAY_PIXKEY=(SANDBOX ? ENV["EFIPAY_PIXKEY_HOM"] : ENV["EFIPAY_PIXKEY_PROD"])
  EFIPAY_API_URL=(SANDBOX ? ENV["EFIPAY_API_URL_HOM"] : ENV["EFIPAY_API_URL_PROD"])
  WEBHOOK_URL=(SANDBOX ? ENV["WEBHOOK_URL_HOM"] : ENV["WEBHOOK_URL_PROD"])
end
